blank_issues_enabled: false
contact_links:
  - name: ğŸ“¨ liebespaar93 ê¹ƒí—ˆë¸Œ í”„ë¡œí•„
    url: https://github.com/liebespaar93/
    about: Please ask and answer questions here.
  - name: ğŸŒ kyoulee í”„ë¡œì íŠ¸
    url: https://github.com/users/liebespaar93/projects/4
    about: Please report security vulnerabilities here.
